# Generated by Django 5.0.7 on 2024-07-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tables',
            new_name='Record',
        ),
    ]
